1.0/sw friends
DonatienGascoin/TopQuizzApi pull request #17
Opened 2017-01-04 10:41 UTC by Datchik

2017-01-04 13:48 UTC, DonatienGascoin requested changes

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +				object.setCode(ReturnCode.ERROR_050);
Si la liste est vide ou null ce n'est pas une erreur, c'est seulement que l'utilisateur n'a n'a pas d'amis
= Pas de code d'erreur

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +    private UserRepository userRepository;
Les repository non rien à faire dans AppService, ils doivent être dans les services associés: (UserRepository doit etre dans UserService)

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +		UserBean userBean = userRepository.findOne(pseudo);
Du coup tu dois utiliser le UserService et pas le repository pour recuperer l'utilisateur

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +			List<User> list = (List<User>) ((ReturnObject) friendsService.getAllFriendsByPseudo(userBean)).getObject();
Renome ta liste pour plus de compréhension (Elle correspon bien à la liste d'amis c'est ça?)

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +					lQuizz = ((List<Quizz>) ((ReturnObject) getAllQuizzesByPseudo(user.getPseudo())).getObject());
Tu ne peux pas ajouter le Quizz dans le User, sinon tu vas créer une boucle en bdd 
Soit tu retourne un User, soit tu retourne un Quizz, mais tu ne peux pas les mettre dans le même objet
(D'après le nom de ta méthode, il faut juste retourner une liste d'User)

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +		return friendsService.addFriendbyPseudo(pseudo, friendPseudo);
Vérifie que les 2 pseudo existent bien avant d'aller dans la méthode de friendService (Regarde dans les autres méthodes comment c'est geré

Ta méthode, passe lui en parametre les 2 users plutot que seulement les pseudos

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +		return friendsService.deleteFriend(pseudo, friendPseudo);
Vérifie que les 2 pseudo existent bien avant d'aller dans la méthode de friendService (Regarde dans les autres méthodes comment c'est geré

Ta méthode, passe lui en parametre les 2 users plutot que seulement les pseudos

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +public class FriendsServiceImpl implements FriendsService {
Le services n'est pas utiles, Friend = List<User>, met plutôt les methodes dans le UserService

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +		log.info("Get all friends by pseudo");
Dans le log rajoute le pseudo (regarde dans les méhodes d'UserService par exemple)

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +			for (UserBean userB : new ArrayList<UserBean>(userBean.getFriends())) {
Ajoute le test
if(CollectionUtils.isNotEmpty(userBean.getFriends()){

}

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +	public ReturnObject addFriendbyPseudo(String pseudo, String friendPseudo) {
Passe les User directement, et pas juste les pseudo

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +		UserBean user2 = userRepository.findOne(friendPseudo);
Du coup les 2 lignes à suprimer

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +		if (user1 == null || user2==null ){
Ce test est inutile, tu dois le tester dans AppService ça, si tu arrives dans la fonction, c'est que les 2 users ne sont pas null

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +				log.error("This person is already your friend. [friendPseudo: " + friendPseudo + " pseudo" + pseudo + "], " + ReturnCode.ERROR_300);
Ajoute return obj;

Comme ça tu ne regarde pas le code d'après

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +			}else{//The person was not a friend yet
Du coup tu peux enlever le else

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +	public ReturnObject deleteFriend(String pseudo, String friendPseudo) {
Passe les Users en parametres au lieu des pseudo

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +			UserBean user2 = userRepository.findOne(friendPseudo);
Du coup lignes à supprimer

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +			if (user1 == null || user2==null ){
Test à faire dans AppService

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +				object.setCode(ReturnCode.ERROR_100);
Ajoute le Return obj;

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +			}else{
Met ça au dessus:
Si ils ne sont pas amis{
-> erreur
-> return obj;
}

remove

2017-01-04 13:48 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +	protected static User getUserByUserBean(UserBean bean) {
remettre ce qu'il y avait avant vu que tu vas supprimer le service Friends pour le mettre dans UserService

2017-01-04 14:22 UTC, Datchik commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +			List<User> list = (List<User>) ((ReturnObject) friendsService.getAllFriendsByPseudo(userBean)).getObject();
Renommé friendList.

2017-01-04 14:24 UTC, Datchik commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +				object.setCode(ReturnCode.ERROR_050);
Corrigé

2017-01-04 14:28 UTC, Datchik commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +					lQuizz = ((List<Quizz>) ((ReturnObject) getAllQuizzesByPseudo(user.getPseudo())).getObject());
A discuter

2017-01-04 14:36 UTC, Datchik commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +		log.info("Get all friends by pseudo");
Ceux avec userBean n'ont pas été fait donc pas d'exemple donc je zap

2017-01-04 14:45 UTC, Datchik commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +	public ReturnObject addFriendbyPseudo(String pseudo, String friendPseudo) {
Fait

2017-01-04 14:46 UTC, Datchik commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +		UserBean user2 = userRepository.findOne(friendPseudo);
Fait

2017-01-04 15:05 UTC, Datchik commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +				log.error("This person is already your friend. [friendPseudo: " + friendPseudo + " pseudo" + pseudo + "], " + ReturnCode.ERROR_300);
Fait

2017-01-04 15:06 UTC, Datchik commented on src/main/java/com/quizz/database/services/impl/FriendsServiceImpl.java
> +			}else{//The person was not a friend yet
Done

2017-01-04 17:02 UTC, DonatienGascoin requested changes

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/repository/UserRepository.java
> +	UserBean findByQuestionPseudo(String pseudo);
A supprimer

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/repository/UserRepository.java.orig
> +
Fichier à supprimer

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/AppService.java.orig
> +
Fichier à supprimer

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +    @Autowired
Fait Crtl + Maj + F

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +		User user = (User)userService.getUser(pseudo).getObject();
Peut planter
Si la methode te retourne null, impossible de faire getObject

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +		if (user == null) {
((User) object.getObject()).getId() != null

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +		List<User> friendList = (List<User>) (userService.getAllFriendsByPseudo(user).getObject());
User user =

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +		List<User> friendList = (List<User>) (userService.getAllFriendsByPseudo(user).getObject());
A changer, à faire en 2 étapes

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +		List<User> friendList = (List<User>) (userService.getAllFriendsByPseudo(user).getObject());
If(list== null)

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +			lQuizz = ((List<Quizz>) ((ReturnObject)getAllQuizzesByPseudo(user.getPseudo())).getObject());
A faire en 2 fois 
Ajouter un test si la liste est vide

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +		object.setCode(ReturnCode.ERROR_000);
Attention à ne pas toujours retourner error_000

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +		User u1 = (User) tmp.getObject();
A utiliser dans addFriends

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +		object.setObject(userService.addFriendbyPseudo(user1, user2));
Non, ta methode retourne un returnObject

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +		return object;
return userService.delete.....

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +		return userService.searchUserByPseudo(pseudo);
Tester si le user existe

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java.orig
> +
Fichier à supprimer

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +		for (User friendBean : friendList) {
utilise User.getFriends()

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +	public ReturnObject getAllFriendsByPseudo(User user) {
Methode à supprimer

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +		log.info("Add friend ");
Ajoute les 2 pseudo au log

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +			log.error("Impossible to add Friend, " + ReturnCode.ERROR_500);
Dans le log, ajoute les name

2017-01-04 17:02 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +			if (user1.getFriends().contains(user2) || user2.getFriends().contains(user1)) {
Inverse if et else, ajoute un return

2017-01-05 13:10 UTC, Datchik commented on src/main/java/com/quizz/database/repository/UserRepository.java
> +	UserBean findByQuestionPseudo(String pseudo);
OK

2017-01-06 13:26 UTC, DonatienGascoin requested changes

2017-01-06 13:26 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/controllers/FriendsController.java
> +public class FriendsController {
Met les méthodes dans UserControlleur, et supprime ce controlleur

2017-01-06 13:26 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/controllers/FriendsController.java
> +	@RequestMapping(value = "/add", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
nome la méthode addFriend du coup

2017-01-06 13:26 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/controllers/FriendsController.java
> +	@RequestMapping(value = "/delete", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
et celle la deleteFriend

2017-01-06 13:26 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/AppService.java
> +	public ReturnObject searchUserByPartialPseudo(String pseudo);
String partialPseudo à la place de pseudo, tu n'as pas un pseudo complet, tu n'en a qu'une partie

2017-01-06 13:26 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/UserService.java
> +	public ReturnObject searchUserByPartialPseudo(String pseudo);
String partialPseudo aussi

2017-01-06 14:45 UTC, merged