[LPT][0.1/addActive] Add active column in USER table in all the API + create methods
DonatienGascoin/TopQuizzApi pull request #3
Opened 2016-11-16 23:02 UTC by paretl

2016-11-17 09:17 UTC, DonatienGascoin requested changes

2016-11-17 09:17 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/controllers/UserController.java
> +	public ResponseEntity<ReturnObject> activeUser(@RequestParam(name = "mail") String email) {
Tu met le param à "mail", et la variable à "email"
Problème de cohérence :)

2016-11-17 09:17 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/controllers/UserController.java
> +		ReturnObject object = null;
Initialise le ReturnObject, sinon tu peux ne rien retourner en JSON, et l'application va planter

2016-11-17 09:17 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/controllers/UserController.java
> +	public ResponseEntity<ReturnObject> checkActive(@RequestParam(name = "mail") String email) {
Idem

2016-11-17 09:17 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/controllers/UserController.java
> +		ReturnObject object = null;
Idem, attention à l'initialisation de tes variables

2016-11-17 09:17 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/modeles/User.java
> +	public User(String pseudo, String password, String mail, Boolean active, Collection<User> friends, Collection<Question> questions) {
Tu as regardé si il n'y avait pas d'impact sur d'autres appelles? 
Il vaut peut être mieux rajouter un constructeur si tu impact trop de service
A vérifier, je ne sais pas la, à toi de voir

2016-11-17 09:17 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +	public ReturnObject activeUser(String email) {
Harmonise les "mail" "email" de partout, utilise toujours la même variable

2016-11-18 13:09 UTC, paretl commented
@DonatienGascoin Modifs faites

2016-11-18 13:18 UTC, DonatienGascoin requested changes

2016-11-18 13:18 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/controllers/UserController.java
>  	public ResponseEntity<?> changePassword(@RequestParam(name = "password") String password,
Attention:
ResponseEntity<?>
Soit tu choisis de mettre:
ResponseEntity<ReturnObject> (tu specifie l'objet de retour)

Soit tu laisse comme ça, mais tu fait une JavaDoc

(Privilégie la première option)

2016-11-18 13:18 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/controllers/UserController.java
> +			@RequestParam(name = "mail") String email) {
Loulou, fait ton harmonisation à fond: 
@RequestParam(name = "mail") String email)
-> @RequestParam(name = "mail") String **mail**)

2016-11-18 13:18 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/controllers/UserController.java
> +			log.error("Impossible to get User [email: " + mail + "]", e);
Attention à tes logs, il ne correspond pas

2016-11-18 13:18 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/controllers/UserController.java
> +			log.error("Impossible to get User [email: " + mail + "]", e);
Idem, attention aux logs

2016-11-18 13:18 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +		User user = (User) userCheckActive.getObject();
Attention: Comment fait tu si getUserByMail n'existe pas?
Ajoute un try catch autour des lignes 319/320 pour te protéger, et adapte ton comportement si tu ne récupère pas d'utilisateur

2016-11-18 13:18 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +			log.info("Check if user is active [pseudo: " + result.getPseudo() + "]");
Met ce log la en haut de la fonction, qu'on sache (en regardant uniquement les logs) dans quelle fonction on se trouve

2016-11-18 13:18 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +					object.setCode(ReturnCode.ERROR_050);
Ajoute un log pour dire que le user n'est pas actif

2016-11-18 13:39 UTC, paretl commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +			log.info("Check if user is active [pseudo: " + result.getPseudo() + "]");
fait

2016-11-18 13:39 UTC, paretl commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +					object.setCode(ReturnCode.ERROR_050);
fait

2016-11-18 13:39 UTC, paretl commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +		User user = (User) userCheckActive.getObject();
fait

2016-11-18 14:41 UTC, paretl commented on src/main/java/com/quizz/database/controllers/UserController.java
> +			log.error("Impossible to get User [email: " + mail + "]", e);
fait

2016-11-18 14:41 UTC, paretl commented on src/main/java/com/quizz/database/controllers/UserController.java
> +			@RequestParam(name = "mail") String email) {
fait

2016-11-18 14:42 UTC, paretl commented
Second changes done
@DonatienGascoin You can check a last time if you want

2016-11-18 19:53 UTC, DonatienGascoin requested changes

2016-11-18 19:53 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +			if (StringUtils.isNotBlank(password)) {
Erreur: Test inutile: tu utilise la variable que tu envoi en parametre de ta fonction (qui n'est jamais nulle) 
Utilise plutôt user.getPassword()

2016-11-18 19:53 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +			if (StringUtils.isNotBlank(mail)) {
Erreur: Test inutile: tu utilise la variable que tu envoi en parametre de ta fonction (qui n'est jamais nulle) 
Utilise plutôt user.getMail()

2016-11-18 19:53 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
> +			object.setCode(ReturnCode.ERROR_000);
A supprimer, peut importe ce que tu va faire, tu va lui mettre ERROR_000
-> Ne marche pas si l'email n'est pas valide
Utilise plutôt le ReturnCode que tu recupère dans le getUserByMail (et celui dans editUser)

2016-11-21 14:53 UTC, paretl commented
@DonatienGascoin Go to work, it's time to check

2016-11-21 16:19 UTC, DonatienGascoin requested changes

2016-11-21 16:19 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/UserServiceImpl.java
>  		object.setObject(result);
Utilise ça: getUserByUserBean(tmp)

2016-11-21 16:41 UTC, DonatienGascoin approved these changes

2016-11-21 17:30 UTC, merged