0.1/sw create quizz
DonatienGascoin/TopQuizzApi pull request #4
Opened 2016-11-24 10:31 UTC by RomainChaz

2016-11-24 16:44 UTC, DonatienGascoin requested changes

2016-11-24 16:44 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/modeles/Theme.java
> +                this.name = name;
Formatage du texte

2016-11-24 16:44 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/repository/ThemeRepository.java
> +	List<ThemeBean >findAll();
Formatage du texte <ThemeBean> findAll ...

2016-11-24 16:44 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/ThemeService.java
> + * @since 31/10/2016
Javadoc to update

2016-11-24 16:44 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/ThemeService.java
> +	public ReturnObject deleteTheme(String name);
Je ne pense pas que tu ai besoin d'une fonction comme ça, mais plutot d'une fonction deleteById:
Depuis android: tu recupère une liste de themes sous la forme id -> name
Du coup tu peux renvoyer l'id à l'API

2016-11-24 16:44 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/AppServiceImpl.java
> +        @Autowired
Formatage

2016-11-24 16:44 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> + * Warning: Never return password !
To delete

2016-11-24 16:44 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +    public ReturnObject getThemeByName(String name){
Comme tout à l'heure, mieux vaut pas passer un id? (Dis moi si non)

2016-11-24 16:44 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +			ThemeBean findByName = themeRepository.findByName(name);
Attention ! Viens me voir qu'on en parle.
 Dans la table Theme tu as un Id_Question, du coup le tu peux potentiellement recupérer plusieurs Theme.

2016-11-24 16:44 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +			object.setCode(ReturnCode.ERROR_000);
object.setCode(000)?
Tu fais comment si ton Theme est vide? Est nul? Tu retourne quand même l'erreur 0?

2016-11-24 16:44 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +                for (ThemeBean themeBean : findAll) {
Potentiellement tu plante, si findAll retourne null

2016-11-24 16:44 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +        object.setCode(ReturnCode.ERROR_000);
object.setCode(000)?
Tu fais comment si ton Theme est vide? Est nul? Tu retourne quand même l'erreur 0?

2016-11-24 16:44 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +        ThemeBean t = theme.convertToBean();
Tu peux mettre de "//Test if..." dans le try, au cas ou tu ai une exception

2016-11-24 16:44 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +                object.setCode(ReturnCode.ERROR_000);
object.setCode(000)?
Tu fais comment si ton Theme est vide? Est nul? Tu retourne quand même l'erreur 0?

2016-11-24 16:44 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +                    //TODO : Attend un String Id (pas un name)
Ne pas oublier soit de la faire, soit de bien le preciser dans le commit

2016-11-25 10:32 UTC, RomainChaz commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +    public ReturnObject getThemeByName(String name){
Je pensais plus à cette fonction pour la suite, en soit peut importe si Id ou name je pense. Je modifierai par la suite si jamais ;)

2016-11-25 12:51 UTC, RomainChaz commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +                for (ThemeBean themeBean : findAll) {
Nop, erreur 200

2016-11-25 12:53 UTC, closed without merging