0.1/sw themes display
DonatienGascoin/TopQuizzApi pull request #5
Opened 2016-11-24 10:37 UTC by Datchik

2016-11-24 17:01 UTC, DonatienGascoin requested changes

2016-11-24 17:01 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/controllers/ThemeController.java
> +	@RequestMapping(value = "/get", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
Attention, depuis android tu doit faire /get pour appeler la fonction getAllTheme
Change /get par /getAll

2016-11-24 17:01 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/controllers/ThemeController.java
> +		object = appService.getAllThemes();
Regarde dans UserRepository la manière de faire, il faut ajouter un Try catch
L'interet de le mettre, c'est si on veut ajouter des surveillances sur le projets, au cas ou il y ai des problème, et d'avoir des log si il y a une erreur

2016-11-24 17:01 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +			tmp = themeRepository.findAll();
Declare et initialise la liste à cette endroit, pas besoin de la déclarer plus tôt

2016-11-24 17:01 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +			for (ThemeBean tB : tmp) {
Tu fais comment si findAll te retourne null? Ajoute un test pour te proteger

2016-11-24 17:01 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +				object.setCode(ReturnCode.ERROR_100);
Par convention, on test d'abord ce qui est juste avant ce qui est faut

2016-11-24 17:01 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +				object.setCode(ReturnCode.ERROR_000);
Met ta boucle à cette endroit par exemple

2016-11-24 17:01 UTC, DonatienGascoin commented on src/main/java/com/quizz/database/services/impl/ThemeServiceImpl.java
> +				th.setId(tB.getId());
Il exite une méthode pour convertir les themes directement: getThemeByThemeBean

2016-12-19 10:46 UTC, paretl approved these changes

2016-12-19 10:49 UTC, DonatienGascoin approved these changes

2016-12-19 12:54 UTC, merged